spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.33.129:3306/ollehboard
    username: root
    password: system
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#aws s3
#aws_access_key_id: ${AWS_ACCESS_KEY_ID} #환경 변수 설정
#aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY} #환경 변수 설정
#aws:
#  region: ap-northeast-2
#  s3:
#    bucket: ollehimagebucket

jwt:
  token:
    secret: "secretKey2G312A3E224A78H51R6dfvnjhgSf3asD3N5KE23Lq"
  access-expired: 3600000    #3600000 1시간
  refresh-expired: 86400000   # 1 day

logging.level:
  org.hibernate.SQL: debug

upload:
  path: C:\Users\zhscl\Desktop\LocalImageRepository

