name: Deploy to EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set executable permissions on Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Run EC2 instance
        run: |
          echo "PRIVATE_KEY" > EC2-KEY-PAIR.pem
          chmod 400 EC2-KEY-PAIR.pem
          ssh -o StrictHostKeyChecking=no -i "EC2-KEY-PAIR.pem" ubuntu@ec2-43-201-9-47.ap-northeast-2.compute.amazonaws.com

      - name: Run the JAR on the EC2 instance
        run: |
          cd /home/ubuntu
          mv /home/ubuntu/boardProject/build/spring.test-0.0.1-SNAPSHOT.jar /home/ubuntu/
          sudo java -jar spring.test-0.0.1-SNAPSHOT.jar
