name: Deploy to EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set executable permissions on Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build bootJar

      - name: Transfer JAR to EC2 instance
        run: |
          echo "PRIVATE_KEY" > EC2-KEY-PAIR.pem
          chmod 600 EC2-KEY-PAIR.pem
          scp -i “EC2-KEY-PAIR.pem” build/libs/OllethBoardProject-0.0.1-SNAPSHOT.jar ubuntu@ec2-43-200-177-149.ap-northeast-2.compute.amazonaws.com:~/OllethBoardProject-0.0.1-SNAPSHOT.jar
          rm -f private_key.pem

      - name: Run the JAR on the EC2 instance
        run: |
          echo "PRIVATE_KEY" > EC2-KEY-PAIR.pem
          chmod 600 EC2-KEY-PAIR.pem
          ssh -i “EC2-KEY-PAIR.pem” ubuntu@ec2-43-200-177-149.ap-northeast2.compute.amazonaws.com "sudo java -jar OllethBoardProject-0.0.1-SNAPSHOT.jar"
