name: Deploy to EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > EC2-KEY-PAIR.pem
          chmod 600 EC2-KEY-PAIR.pem
          ssh -o StrictHostKeyChecking=no -i "EC2-KEY-PAIR.pem" ubuntu@ec2-43-2019-47.ap-northeast-2.compute.amazonaws.com

      - name: Set executable permissions on Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          echo "$(ls)"
          cd boardProject
          ./gradlew clean bootJar
          
      - name: Run the JAR on the EC2 instance
        run: |
          echo "$(ls)"
          find /boardProject/build/libs -name 'spring.test-0.0.1-SNAPSHOT.jar' -exec sudo java -jar {} \;

